remote_theme: pages-themes/slate@v0.2.0
title: "Packed to the Brim: Analyzing Highly Responsive Prefixes on the Internet"
author: "Anonymous Authors"
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

description: "Get access to the data used in the paper and our continuous scan results"